- name: Configure App
  hosts: app
  become: true
  vars:
   db_host: "{{ internal_ip_db }}"
  tasks:
    - name: Install soft
      ansible.builtin.package:
        name: git
        state: present


    - name: Add unit file for Puma
      copy:
        src: files/puma.service
        dest: /etc/systemd/system/puma.service
      notify:
        - reload systemd


    - name: Add config for DB connection
      template:
        src: templates/db_config.j2
        dest: /home/appuser/db_config
        owner: appuser
        group: appuser

    - name: Fetch the latest version of application code
      become: true
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: /home/appuser/reddit
        version: monolith


    - name: bundle install
      bundler:
        state: present
        chdir: /home/appuser/reddit

    - name: enable puma
      systemd:
        name : puma
        enabled : true
        state : started

  handlers:
  - name: reload puma
    systemd: name=puma state=restarted
  - name: reload systemd
    command: systemctl daemon-reload
