---
- name: Deploy app
  hosts: app


  tasks:
    - name: Fetch the latest version of application code
      become: true
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: /home/appuser/reddit
        version: monolith
      notify: restart puma

    - name: bundle install
      bundler:
        state: present
        chdir: /home/appuser/reddit

    - name: start  puma
      systemd:
        name : puma
        state : started

  handlers:
  - name: restart puma
    become: true
    systemd: name=puma state=restarted
