plugin: yc_compute
folders:
  - b1gvj6fqqjq8dskoa93o
filters:
  - status == 'RUNNING'
auth_kind: serviceaccountfile
service_account_file: /home/swenum/key_yandex.json
compose:
  ansible_host: network_interfaces[0].primary_v4_address.one_to_one_nat.address
keyed_groups:
  - key: labels['tags']
