all:
  hosts:
      app:
        ansible_host: 158.160.122.72
      db:
        ansible_host: 158.160.113.149
  vars:
    remote_user : appuser
    private_key_file : /home/swenum/.ssh/otus2023
    internal_ip_db :  192.168.10.23
